services:
  db:
    image: postgres:15
    container_name: postgres-woo-db
    environment:
      POSTGRES_USER: user_woo
      POSTGRES_PASSWORD: password_woo
      POSTGRES_DB: woocommerce_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
